### ISSUE TITLE
Permission is not working

### ISSUE THREAD

**Issue by hirale** [mageprince/magento2-productAttachment#25]
Hi,

When  create a role with permission actived, logged as an user with that role. it shows nothing.
![20180509194703](https://user-images.githubusercontent.com/22028058/39830493-ea52bd56-53c1-11e8-88b8-065dcfadc407.png)
![20180509194858](https://user-images.githubusercontent.com/22028058/39830543-09923d04-53c2-11e8-8061-00739400c2b8.png)

Thank you.

**Comment by mageprince** [comment]
@Naturegreen,
Thank you for your report.
The issue has been fixed in [mageprince/magento2-productAttachment#30](https://github.com/mageprince/magento2-productAttachment/pull/30) by @AndreKlang 

Related commit:
[be070802](https://github.com/mageprince/magento2-productAttachment/commit/0779c29a45aea99e950ccb7fc0a82008be070802)
